name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update and upgrade system
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Install Maven and JDK 17
      run: |
        sudo apt-get install -y maven
        sudo apt-get install -y openjdk-17-jdk

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile
      run: mvn compile

    - name: Build
      run: mvn package -DskipTests=true

    - name: Test
      run: mvn test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t iscanprint/mission:2.1 .
        docker push iscanprint/mission:2.1
